title: 'helpful.wiki'
googleAnalytics: 'G-D9NWWK7881'
module:
  imports:
    # ${HUGO_MODULE_REPLACEMENTS} set in .zshrc determines the
    # local path to this module's repo on the file system
    path: 'github.com/austintraver/doctober'
    ignoreConfig: false
staticDir:
  - 'static/favicon'
  - 'static/css'
  - 'static/js'
  - 'static/img'
  - 'static'
languageCode: 'en-US'
watch: true
sitePagesMenu: 'main'
newContentEditor: 'nvim'
relativeURLs: true
enableInlineShortcodes: true
enableGitInfo: false
pygmentsUseClasses: true
pluralizeLinkTitles: false
uglyurls: false
minify:
  minifyOutput: false
permalinks:
  /: '/:section/:filename'
frontmatter:
  date: [ 'date', ':default' ]
  lastmod: [ ':fileModTime', ':default' ]
deployment:
  targets:
params:
  mainSections:
    - 'posts'
disableKinds:
  - 'taxonomy'
  - 'term'
  - 'RSS'
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: false
    lineNoStart: 1
    tabWidth: 2
    lineNumbersInTable: false
    tabwidth: 4
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github-ascii
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false
