title: 'Helpful Wiki'
baseURL: 'https://helpful.wiki/'
languageCode: 'en-US'
watch: true
googleAnalytics: 'G-D9NWWK7881'
sitePagesMenu: 'main'
newContentEditor: 'nvim'
relativeURLs: true
enableInlineShortcodes: true
enableGitInfo: false
pygmentsUseClasses: true
pluralizeLinkTitles: false
minify:
  minifyOutput: false
staticDir:
  - 'static'
  - 'static/favicon'
permalinks:
  'posts': '/blog'
frontmatter:
  date: [ 'date', ':default' ]
  lastmod: [ ':fileModTime', ':default' ]
deployment:
  targets:
params:
  mainSections:
    - 'posts'
disableKinds:
  - 'taxonomy'
  - 'term'
  - 'RSS'
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github-ascii
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: false
    lineNoStart: 1
    tabWidth: 2
    lineNumbersInTable: false
    noClasses: true
    style: 'dracula'
    tabwidth: 4
#outputFormats:
#  Algolia:
#    #  tells the output format how to look for the Hugo layout for this output format
#    baseName: 'algolia'
#    # tells the output format to use GoLang’s plain text parser for the layout,
#    # preventing some automatic HTML formatting from ruining your JSON
#    isPlainText: true
#    # tells the output format what kind of file to output.
#    mediaType: 'application/json'
#    # tells the output format not to be included when looping over
#    # the .AlternativeOutputFormats page variable
#    notAlternative: true
#params:
#  algolia:
#    # sets the page variables in which you want included in your index.
#    vars: ['title', 'summary', 'date', 'publishdate', 'expirydate', 'permalink']
#    # sets the custom page params in which you want included in your index.
#    params: ['categories', 'tags']
