baseURL: "https://helpful.wiki/"
title: "Helpful Wiki"
staticDir:
  - "static/css"
  - "static/js"
  - "static/img"
languageCode: "en-us"
publishDir: "docs"
relativeURLs: true
enableInlineShortcodes: true
enableGitInfo: true
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: false
    lineNos: false
    tabWidth: 4
    style: "dracula"
permalinks:
  posts: "/:title"
frontmatter:
  date: [":git"]
