baseURL = "https://helpful.wiki/"
title = "Helpful Wiki"
staticDir = ["static/css", "static/js", "static/img"]
languageCode = "en-us"
publishDir = "docs"
relativeURLs = true
[markup]
    [markup.highlight]
        style = "dracula"
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[permalinks]
    posts = "/:title"
[frontmatter]
    modified = ["modified", ":fileModTime"]
    date = ["date", "modified"]
