baseURL = "https://helpful.wiki/"
title = "Helpful Wiki"
staticDir = ["static/css", "static/js", "static/img"]
languageCode = "en-us"
publishDir = "docs"
[markup]
  [markup.highlight]
    style = "dracula"
