# ------------------------------------------------------------------------------
# doctober config.yaml
# https://gohugo.io/getting-started/configuration/
watch: true
buildDrafts: true
buildExpired: true
buildFuture: true
disableFastRender: true
disableLiveReload: false
disableHugoGeneratorInject: true
# ------------------------------------------------------------------------------
# wiki config.yaml
baseURL: 'http://heike.local:1313'
