# ------------------------------------------------------------------------------
# https://gohugo.io/getting-started/configuration/
watch: true
buildDrafts: true
buildExpired: true
buildFuture: true
disableFastRender: true
disableLiveReload: false
disableHugoGeneratorInject: true
# ------------------------------------------------------------------------------
# wiki config.yaml
baseURL: 'http://localhost:1313'
