# https://gohugo.io/getting-started/configuration/
watch: true
buildDrafts: true
buildExpired: true
buildFuture: true
disableHugoGeneratorInject: true
disableKinds: ['RSS', 'robotsTXT', '404']
disableFastRender: false
disableLiveReload: false
baseURL: 'http://heike.local:1313'
