# ------------------------------------------------------------------------------
# doctober config.yaml
# https://gohugo.io/getting-started/configuration/
buildDrafts: false
buildExpired: false
buildFuture: false
enableRobotsTXT: true
# ------------------------------------------------------------------------------
# wiki config.yaml
baseURL: 'https://helpful.wiki/'
